spring:
  application.name: service
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    consumer:
      auto-offset-reset: earliest
      group-id: gov-audit-service
  zipkin:
    baseUrl: ${ZIPKIN_URL}
    sender:
      type: web
  sleuth:
    web:
      additional-skip-pattern: "/actuator/.*"
    sampler:
      probability: ${ZIPKIN_SAMPLE_RATE:0.1}
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false

logging.config: "classpath:${LOGBACK_CONFIG_FILE:logback-spring.xml}"

management:
  endpoints.web:
    exposure.include: ping, health, heapdump, threaddump, loggers, prometheus, jolokia, hawtio
  endpoint.health.show-details: always

springfox:
  documentation:
    swagger-ui:
      base-url: /actuator/

hawtio:
  authenticationEnabled: false

gov-endpoint:
  service:
    url: ${GOVENDPOINT_SERVICE_URL:http://important.gov:8080}

app:
  service:
    url:
      customers: ${CUSTOMER_SERVICE_UPSTREAM_URL:http://customers.svc:8080}